In [1]:
from HTOCThreatConnect import get_v3_threatconnect_data

In [ ]:
df = get_v3_threatconnect_data(lastObserved_date='2023-01-01', indicatorActive=False, bothActivities=True)
display(df)

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,...,active,activeLocked,dnsActive,whoisActive,legacyLink,tags.data,associatedGroups.data,source,size,indicator
0,5629499567007562,2025-09-05T13:32:42Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-10-30T11:52:40Z,3.0,73.0,"INC9225531, INC9225531",...,True,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 23769, 'name': 'VA CSOC CTS Splunk', '...",NaN,NaN,NaN,prod-barium-us-west-74.li.binaryedge.ninja
1,5629499537002037,2025-04-20T17:12:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-10-30T11:42:32Z,3.0,24.0,Malicious domain reported in new LegionLoader ...,...,True,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,NaN,irp.cdn-website.com
2,5271607,2025-01-29T16:27:10Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-10-30T11:42:20Z,3.0,67.0,The following list of urls and domains are cur...,...,True,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...","[{'id': 548570, 'dateAdded': '2025-01-29T16:27...",NaN,NaN,cdn.deepseek.com
3,6755399442005033,2025-02-12T20:12:22Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-30T11:37:09Z,3.0,46.0,Unwanted IPs Scanning NIH Networks.,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 38933, 'name': 'Active Scanning: Scann...","[{'id': 6755399442001349, 'dateAdded': '2025-0...",NaN,NaN,222.249.237.13
4,5629499535005059,2025-02-12T20:09:47Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-30T11:36:35Z,4.0,48.0,Unwanted IPs Scanning NIH Networks,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 38933, 'name': 'Active Scanning: Scann...","[{'id': 6755399442001348, 'dateAdded': '2025-0...",NaN,NaN,116.98.171.207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3631,223630,2016-12-13T19:56:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,URL,2023-05-18T20:50:10Z,3.0,89.0,HTTP Referer sending victims to exploit kit la...,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 23769, 'name': 'VA CSOC CTS Splunk', '...","[{'id': 39224, 'dateAdded': '2016-12-13T17:57:...",NaN,NaN,http://www.zenpad.org/
3632,223570,2016-12-13T19:56:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,URL,2023-03-31T18:50:10Z,3.0,89.0,HTTP Referer sending victims to exploit kit la...,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 23769, 'name': 'VA CSOC CTS Splunk', '...","[{'id': 39224, 'dateAdded': '2016-12-13T17:57:...",NaN,NaN,http://www.fultonarts.org/index.php/art-centers
3633,4312413,2023-03-27T12:00:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2023-03-28T12:00:42Z,5.0,100.0,File IOCs observed targeting HHS via malspam c...,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35367, 'name': 'hhs-2023032801', 'last...","[{'id': 149124, 'dateAdded': '2023-03-27T12:00...",API ingestion - R&F,327719.0,913283BB9EB72DFAD5005436B07BBD38
3634,4307013,2023-03-12T12:00:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2023-03-12T12:00:26Z,5.0,100.0,Malicious File Hash Indicators and Malspam inf...,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35156, 'name': 'hhs-2023031201', 'last...","[{'id': 148462, 'dateAdded': '2023-03-12T12:00...",API ingestion - R&F,808599.0,FD1390C116CE2AEB7F41F4841A8898A7
3635,223610,2016-12-13T19:56:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,URL,2022-08-12T15:50:16Z,3.0,89.0,HTTP Referer sending victims to exploit kit la...,...,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 23769, 'name': 'VA CSOC CTS Splunk', '...","[{'id': 39224, 'dateAdded': '2016-12-13T17:57:...",NaN,NaN,http://www.southhillsortho.com/contact/contact/

In [1]:
from HTOCThreatConnect import get_v2_threatconnect_data

In [13]:
df = get_v2_threatconnect_data(dateObserved=None)
display(df)

[DEBUG] status=200
[DEBUG] Retrieved 776 observed indicators for HTOC Org on 2025-11-18

,observationCount,lastObserved,userObservedList,indicator
0,7402732,2025-11-18T13:03:51Z,"[{'userName': '35664937356778434955', 'fullNam...",79.124.49.226
1,1820026,2025-11-18T13:43:13Z,"[{'userName': '35664937356778434955', 'fullNam...",91.191.209.74
2,1641032,2025-11-18T13:03:52Z,"[{'userName': '35664937356778434955', 'fullNam...",91.191.209.198
3,1494011,2025-11-18T13:43:13Z,"[{'userName': '35664937356778434955', 'fullNam...",5.188.206.46
4,462623,2025-11-18T13:31:06Z,"[{'userName': '50189120947314147395', 'fullNam...",204.76.203.254
...,...,...,...,...
771,1,2025-11-18T07:03:36Z,"[{'userName': '15920309593055310684', 'fullNam...",3.143.152.247
772,1,2025-11-18T10:38:06Z,"[{'userName': '50189120947314147395', 'fullNam...",92.119.63.254
773,1,2025-11-18T11:33:20Z,"[{'userName': '15920309593055310684', 'fullNam...",185.242.226.80
774,1,2025-11-18T09:08:04Z,"[{'userName': '50189120947314147395', 'fullNam...",metalhoz.com
775,1,2025-11-18T07:31:45Z,"[{'userName': '74198686107399967946', 'fullNam...",104.152.52.216