In [1]:
from HTOCThreatConnect import get_v3_threatconnect_data

In [2]:
df = get_v3_threatconnect_data(lastObserved_date='2024-01-01')
display(df)

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,privateFlag,active,activeLocked,dnsActive,whoisActive,legacyLink,tags.data,associatedGroups.data,source,indicator
0,6755399448243167,2025-05-29T13:34:42Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-09-30T14:23:55Z,0.0,0.0,"Based on open source intelligence, it was iden...",False,True,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 494539, 'name': 'NIH CTI', 'lastUsed':...","[{'id': 5629499541007177, 'dateAdded': '2025-0...",NaN,graphqlnetwork.pro
1,6755399448251593,2025-05-30T13:30:26Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-09-30T14:23:53Z,1.0,63.0,CMS received a volumetric alert for thirty six...,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...","[{'id': 6755399448004487, 'dateAdded': '2025-0...",NaN,89.248.163.79
2,6755399448037607,2025-05-28T19:30:49Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-09-30T14:23:52Z,1.0,77.0,TASK0890150,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 1707685, 'name': 'Bulgaria', 'lastUsed...",NaN,NaN,5.188.206.114
3,6755399467419654,2025-08-13T11:48:32Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-09-30T14:22:51Z,3.0,74.0,INC9191888,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,125.88.174.211
4,5629499563359458,2025-08-13T11:48:33Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-09-30T14:22:51Z,3.0,74.0,INC9191888,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,121.152.230.177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3540,4481963,2023-11-30T13:07:27Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2023-12-01T11:39:58Z,4.0,82.0,"On Nov 29, 2023, the VA was alerted to a crede...",False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 38829, 'name': 'Phishing', 'descriptio...","[{'id': 289531, 'dateAdded': '2023-11-30T13:05...",https://bmwag-rt-prod2-t.campaign.adobe.com,bmwag-rt-prod2-t.campaign.adobe.com
3541,4470013,2023-11-07T16:00:43Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2023-11-12T23:22:07Z,4.0,80.0,vulnerability in the Web User Interface (Web U...,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 242905, 'name': 'Zero Day', 'lastUsed'...","[{'id': 274787, 'dateAdded': '2023-10-20T16:35...",NaN,45.55.134.29
3542,4352800,2023-06-08T16:47:19Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2023-06-09T10:26:16Z,3.0,61.0,NaN,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 36574, 'name': 'XeGroup', 'lastUsed': ...","[{'id': 153532, 'dateAdded': '2023-06-08T15:36...",https://www.meiersupply.com/,www.meiersupply.com/
3543,4352799,2023-06-08T16:47:19Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2023-06-09T10:26:16Z,3.0,61.0,NaN,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 36574, 'name': 'XeGroup', 'lastUsed': ...","[{'id': 153532, 'dateAdded': '2023-06-08T15:36...",https://www.emergencylighting.com/,www.emergencylighting.com/
3544,223610,2016-12-13T19:56:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,URL,2022-08-12T15:50:16Z,3.0,89.0,HTTP Referer sending victims to exploit kit la...,False,True,False,NaN,NaN,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 23769, 'name': 'VA CSOC CTS Splunk', '...","[{'id': 39224, 'dateAdded': '2016-12-13T17:57:...",NaN,http://www.southhillsortho.com/contact/contact/

In [3]:
from HTOCThreatConnect import get_v2_threatconnect_data

In [4]:
df = get_v2_threatconnect_data()
display(df)

[DEBUG] status=200
[DEBUG] Retrieved 774 observed indicators for HTOC Org on 2025-09-30

,observationCount,lastObserved,userObservedList,indicator
0,4045310,2025-09-30T14:04:26Z,"[{'userName': '13520457953477229971', 'fullNam...",78.128.113.190
1,3164958,2025-09-30T14:03:46Z,"[{'userName': '13520457953477229971', 'fullNam...",45.142.193.49
2,1653203,2025-09-30T14:04:33Z,"[{'userName': '64853912235916233429', 'fullNam...",5.188.206.46
3,628265,2025-09-30T07:33:19Z,"[{'userName': '13520457953477229971', 'fullNam...",172.232.188.177
4,613522,2025-09-30T07:33:58Z,"[{'userName': '50189120947314147395', 'fullNam...",66.175.208.166
...,...,...,...,...
769,1,2025-09-30T10:00:57Z,"[{'userName': '64853912235916233429', 'fullNam...",45.84.107.222
770,1,2025-09-30T05:34:41Z,"[{'userName': '74198686107399967946', 'fullNam...",brppharma.com
771,1,2025-09-30T13:32:00Z,"[{'userName': '74198686107399967946', 'fullNam...",academy4sc.org
772,1,2025-09-30T05:31:26Z,"[{'userName': '13520457953477229971', 'fullNam...",104.244.73.193
773,1,2025-09-30T01:31:19Z,"[{'userName': '13520457953477229971', 'fullNam...",27.43.207.128