In [1]:
from HTOCThreatConnect import get_v3_threatconnect_data

In [3]:
df = get_v3_threatconnect_data(lastObserved_date='2025-01-01', indicatorActive=False)
display(df)

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,privateFlag,active,activeLocked,legacyLink,tags.data,associatedGroups.data,source,dnsActive,whoisActive,indicator
0,6755399443033831,2025-04-11T17:46:49Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-14T16:14:24Z,4.0,65.0,(U//FOUO) Federal law enforcement and the Inte...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...","[{'id': 6755399443004631, 'dateAdded': '2025-0...",NaN,NaN,NaN,194.26.29.44
1,5629499566201482,2025-09-03T14:54:47Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-14T15:13:47Z,3.0,75.0,INC9219946,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35760, 'name': 'OS Splunk API', 'descr...",NaN,NaN,NaN,NaN,141.98.10.225
2,6755399443033495,2025-04-11T17:27:17Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-14T14:14:09Z,1.0,46.0,Executive Summary: \n\nThe following IP addre...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 1707685, 'name': 'Bulgaria', 'lastUsed...","[{'id': 6755399444000503, 'dateAdded': '2025-0...",NaN,NaN,NaN,194.180.49.70
3,4808308,2024-08-07T15:39:11Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-14T10:53:35Z,4.0,43.0,BugSleep is a custom backdoor Muddy Water has ...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...","[{'id': 454519, 'dateAdded': '2024-09-04T15:06...",NaN,NaN,NaN,31.171.154.54
4,4329688,2023-05-05T13:15:25Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-10-14T10:53:30Z,1.0,5.0,https://socradar.io/dark-web-profile-blackcat-...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 1466757, 'name': 'BlackCat', 'lastUsed...","[{'id': 150524, 'dateAdded': '2023-05-05T13:13...",NaN,NaN,NaN,23.216.147.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,4403362,2023-09-17T13:21:38Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-03-09T08:32:14Z,3.0,0.0,NaN,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 39761, 'name': 'darkgate', 'lastUsed':...","[{'id': 162887, 'dateAdded': '2023-09-17T13:20...",NaN,False,False,www.zerofox.com
947,4299533,2023-02-15T15:04:33Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-03-06T08:31:22Z,4.0,0.0,These are socgholish cases or fake update. Wi...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 39624, 'name': 'HHS Splunk Production ...","[{'id': 138694, 'dateAdded': '2022-07-12T00:01...",NaN,NaN,NaN,173.254.104.138
948,4319206,2023-04-10T14:30:12Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-02-22T07:16:02Z,3.0,0.0,The Cybersecurity and Infrastructure Security ...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35760, 'name': 'OS Splunk API', 'descr...","[{'id': 150135, 'dateAdded': '2023-04-25T18:20...",NaN,NaN,NaN,79.98.104.4
949,4720935,2024-06-17T18:11:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-02-12T07:16:09Z,1.0,0.0,**(U//FOUO) Additional Indicators of Compromis...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 275467, 'name': 'Cyber Intelligence Ne...","[{'id': 345639, 'dateAdded': '2024-06-17T17:59...",NaN,NaN,NaN,205.169.39.195
950,4402865,2023-09-15T19:51:29Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-01-23T07:36:38Z,3.0,0.0,A malvertising campaign is targeting corporate...,False,False,False,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 39704, 'name': 'Antivirus evasion', 'l...","[{'id': 162660, 'dateAdded': '2023-09-15T19:51...",NaN,NaN,NaN,31.31.196.208

In [3]:
from HTOCThreatConnect import get_v2_threatconnect_data

In [4]:
df = get_v2_threatconnect_data()
display(df)

[DEBUG] status=200
[DEBUG] Retrieved 774 observed indicators for HTOC Org on 2025-09-30

,observationCount,lastObserved,userObservedList,indicator
0,4045310,2025-09-30T14:04:26Z,"[{'userName': '13520457953477229971', 'fullNam...",78.128.113.190
1,3164958,2025-09-30T14:03:46Z,"[{'userName': '13520457953477229971', 'fullNam...",45.142.193.49
2,1653203,2025-09-30T14:04:33Z,"[{'userName': '64853912235916233429', 'fullNam...",5.188.206.46
3,628265,2025-09-30T07:33:19Z,"[{'userName': '13520457953477229971', 'fullNam...",172.232.188.177
4,613522,2025-09-30T07:33:58Z,"[{'userName': '50189120947314147395', 'fullNam...",66.175.208.166
...,...,...,...,...
769,1,2025-09-30T10:00:57Z,"[{'userName': '64853912235916233429', 'fullNam...",45.84.107.222
770,1,2025-09-30T05:34:41Z,"[{'userName': '74198686107399967946', 'fullNam...",brppharma.com
771,1,2025-09-30T13:32:00Z,"[{'userName': '74198686107399967946', 'fullNam...",academy4sc.org
772,1,2025-09-30T05:31:26Z,"[{'userName': '13520457953477229971', 'fullNam...",104.244.73.193
773,1,2025-09-30T01:31:19Z,"[{'userName': '13520457953477229971', 'fullNam...",27.43.207.128